### PR TITLE
[FIX] Notification permission timing

### LINKED ISSUE #110: [FIX] Ask notification permission using same strategy as location permission

### PR DESCRIPTION
**Pull request by Laurarestrepo03**
- Closes #110 
- Changes notification permission timing, so now it's not done after login, it's done every app launch. Please remember that the `askPermission()` function only asks permission if it hasn't been asked before, not every time it's called, meaning that it won't ask permission every time the app is opened.
- Fixes bug where uninstalling and re-installing the app deleted the permission but didn't ask for it again
- Although it doesn't use the same strategy as the location permission (see the comment I made inside the issue), it has the same timing, so both permissions will be asked subsequently 

Lmk if you have any questions or want changes made

### CODE REVIEW

File: FoodBookApp/Handlers/NotificationHandler.swift [hunk 1]
```diff
@@ -37,6 +38,7 @@ class NotificationHandler {
                 
         let content = UNMutableNotificationContent()
         content.title = "We miss you..."
+        // FIXME: You haven't left a review in X days, depending on settings
```
Comment (Laurarestrepo03) [inline FoodBookApp/Handlers/NotificationHandler.swift:41]: This is a FIXME for #164

File: FoodBookApp/Handlers/NotificationHandler.swift [hunk 2]
```diff
@@ -15,6 +15,7 @@ class NotificationHandler {
         { success, error in
             if success {
                 print("Access granted!")
+                self.sendLastReviewNotification(date: Date())
```
Comment (mar-cas3) [inline FoodBookApp/Handlers/NotificationHandler.swift:18]: question, why does the method need to be called here? wouldn't it send a notification right away since it's with the default date?

Comment (Laurarestrepo03) [reply FoodBookApp/Handlers/NotificationHandler.swift:18]: It's called here bc once notifications are approved, it will schedule one for the first time since otherwise it would only send one if they make a review, so if they never do, it will never encourage them to. Also, this function receives today's date and within it adds up the four days, check the triggerDar variable:
```swift
func sendLastReviewNotification(date: Date) {
        
        let notificationIdentifier = "lastReviewNotification"

        cancelNotification(identifier: notificationIdentifier)
                    
        let triggerDate = Calendar.current.date(byAdding: .day, value: 4, to: date)!
        
        let trigger = UNCalendarNotificationTrigger(dateMatching: Calendar.current.dateComponents([.year, .month, .day, .hour, .minute, .second], from: triggerDate), repeats: false)
                
        let content = UNMutableNotificationContent()
        content.title = "We miss you..."
        content.body = "You haven't left a review in a while"
        content.sound = UNNotificationSound.default
        
        let request = UNNotificationRequest(identifier: notificationIdentifier, content: content, trigger: trigger)
        
        UNUserNotificationCenter.current().add(request)
    }

```

Comment (Laurarestrepo03) [reply FoodBookApp/Handlers/NotificationHandler.swift:18]: I only changed where it's called (bc before it was triggered regardless of whether or not permission was given), not the way it works, it has always received the current date.

Comment (Laurarestrepo03) [reply FoodBookApp/Handlers/NotificationHandler.swift:18]: I could move to outside the if, just in case they turn on notifications during that four day span. If they remain off, the notification won't be visible so it's not a problem. But either way the date is okay :)

Comment (mar-cas3) [reply FoodBookApp/Handlers/NotificationHandler.swift:18]: Okay, i understand!! Thank you!!

Comment (mar-cas3) [reply FoodBookApp/Handlers/NotificationHandler.swift:18]: @Laurarestrepo03 please re-request a review from me so i can approve!!

**Review by mar-cas3 — APPROVED** [review]
Meme Reaction GIF

File: FoodBookApp/Handlers/NotificationHandler.swift (hunk 2 above)
Comment (Laurarestrepo03) [reply FoodBookApp/Handlers/NotificationHandler.swift:18]: Thank you! I saw you approved the PR, so I'll make that small change and merge :p

Comment (juanyepesp) [inline FoodBookApp/Handlers/NotificationHandler.swift:18]: I know this is not that big of a deal but since you wanted to change this, I am marking it for change

**Review by juanyepesp — CHANGES_REQUESTED** [review]
See comment above, and thank you!

**Comment by Laurarestrepo03** [comment]
**Commit 41d021e18109c44170ba25b21b767231573d2bcb:**

@mar-cas3 @juanyepesp Decided to remove the line altogether since the BQ goes "How many days have passed since the user _last_ left a review?", meaning I'll only trigger when they leave a review. Lmk if you have any questions or want changes made

**Review by juanyepesp — APPROVED** [review]
looks awesome!
