### PR TITLE
[FIX] Assure geofence creation.

### LINKED ISSUE #66: [FIX] Geofence not being created on all paths
When location was not determined initially and then changed the geofence wasn't being set up.

### PR DESCRIPTION
**Pull request by mar-cas3**
Moves geofence creation to constructor of LocationServices to ensure it is always created.

Closes #66

### CODE REVIEW

File: FoodBookApp/Services/LocationService.swift [hunk 1]
```diff
@@ -21,10 +21,10 @@ final class LocationService: NSObject, ObservableObject {
         self.manager.delegate = self
         self.manager.desiredAccuracy = kCLLocationAccuracyBest
         self.manager.startUpdatingLocation()
+        setupGeofence(for: uniandesLocation, regionRadius: 400, identifier: "uniandes")
```
Comment (juanyepesp) [inline FoodBookApp/Services/LocationService.swift:24]: could you explain a bit why this change was necessary? thanks

**Review by juanyepesp — COMMENTED** [review]
i just have that one inquiry (check above) but overall looks great

File: FoodBookApp/Services/LocationService.swift (hunk 1 above)
Comment (mar-cas3) [reply FoodBookApp/Services/LocationService.swift:24]: when testing, i realized that there was only one specific path in which the geofence was being created: the user opens the app and right away gets prompted for access and they click while using. however through testing and reinstalling the app, since those settings are saved, there wasn't a need to request access and thus the fence was not being created. this ensures that regardless of when a user accepts access to location, the geofence is created and the CAS will work as expected.

Comment (juanyepesp) [reply FoodBookApp/Services/LocationService.swift:24]: got it, looks awesome then

**Review by juanyepesp — APPROVED** [review]
looks good!
